# Generated by Django 4.2.30 on 2026-05-25 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0150_submissionanalysis_alter_contest_private_contestants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionanalysis',
            options={'verbose_name': 'submission analysis', 'verbose_name_plural': 'submission analyses'},
        ),
        migrations.AddField(
            model_name='problem',
            name='sae_bounds',
            field=models.JSONField(blank=True, default=dict, verbose_name='SAE bounds cache'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sae_max_penalty',
            field=models.PositiveIntegerField(default=50, help_text='Maximum percentage by which the score can be reduced for poor code quality (0 to 100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SAE maximum penalty (%)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sae_metrics_config',
            field=models.JSONField(blank=True, default={'avg_identifier_length': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'branch_count': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'comment_ratio': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'cyclomatic_complexity': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'halstead_difficulty': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'halstead_effort': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'halstead_volume': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'keyword_goto_count': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'loop_count': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'magic_number_count': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'maintainability_index': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'max_line_length': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'modularity_ratio': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'nesting_depth': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'sloc': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'source_char_count': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'structural_duplication_ratio': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'total_var_name_length': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}, 'unique_identifiers': {'direction': 'lower_better', 'enabled': False, 'weight': 1.0}}, help_text='JSON configuration for static analysis.', verbose_name='SAE metrics configuration'),
        ),
        migrations.AddField(
            model_name='submissionanalysis',
            name='final_score',
            field=models.FloatField(default=0.0, verbose_name='final score'),
        ),
        migrations.AddField(
            model_name='submissionanalysis',
            name='sae_score',
            field=models.FloatField(default=0.0, verbose_name='SAE multiplier'),
        ),
        migrations.AlterField(
            model_name='submissionanalysis',
            name='analysis_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='analysis timestamp'),
        ),
        migrations.AlterField(
            model_name='submissionanalysis',
            name='metrics',
            field=models.JSONField(default=dict, help_text='Flexible JSON field storing all extracted tree-sitter metrics.', verbose_name='metrics data'),
        ),
    ]
